### ISSUE TITLE
pipeline processing

### ISSUE THREAD

**Issue by chmike** [myntra/pipeline#1]
The simple example shows a sequential stage processing. It is unclear from the documentation and the example if work could be processed concurrently by the pipeline. If not, what would be required to support concurrent processing.

**Comment by adnaan** [comment]
Hi, 
     Thanks for the review! Pipeline can do both concurrent and sequential work. It's configured while creating a stage:

`pipeline.NewStage("mypworkstage", true, false)`

where `concurrent=true` for concurrent processing of work. See [NewStage](https://godoc.org/github.com/myntra/pipeline#NewStage) .

I have updated the Readme, to try and explain concurrent behaviour better: https://github.com/myntra/pipeline#usage. Does this help?

**Comment by chmike** [comment]
The confusion result from a misunderstanding of what you meant by the pipeline concept. 

I also have to implement a pipeline but it's different. In my case work is injected in the pipeline and has to go through a sequence of processing steps. Multiple work can go through the sequence of processing steps concurrently. It is a different working model than the one proposed by your pipeline package.

However, your code is very well written. I will inspire myself from it. Thank you very much from sharing it.

**Comment by adnaan** [comment]
Thanks! Let me know if you need further clarification.
