### ISSUE TITLE
result is empty when concurrent stage

### ISSUE THREAD

**Issue by seanjoe** [myntra/pipeline#6]
in result_group.go func run() 
when Error == nil should g.result = result
and in stage.go func run()
many steps results should merge

**Comment by adnaan** [comment]
looking into it.

**Comment by wjkxiaowu** [comment]
it is always return &Result{} when concurrent stage run ???

**Comment by shaikemarc** [comment]
Any update on this one? thanks!

**Comment by adnaan** [comment]
@shaikemarc This PR: https://github.com/myntra/pipeline/pull/9 has been dangling in my local for a while. Just pushed it. Would love your feedback if it works. Will test more and merge later.

**Comment by shaikemarc** [comment]
@adnaan ,
thanks for the quick response. 
I tried your latest commit and it seems that mergeResult panics on a nil map assignment (g.result.KeyVal). 
When fixed it locally by simply instantiate it, it didn't panic but i still got an empty map..
Just a clarification: I used your simple example and changed the concurrent flag to true...

**Comment by adnaan** [comment]
Updated the PR. 

Have tested the simple example and go test -v. Runs ok but might still have bugs. Will try to get it merged by this weekend.

**Comment by shaikemarc** [comment]
Thanks again for your quick response.
